# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  #push:
  #  branches: [ "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build & Release
    runs-on: macos-latest

    steps:
      # Checkout repository
      - uses: actions/checkout@v4
      
      # Setup Java
      - name: Set Up Java
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'oracle'
          java-version: '17'

      # Setup flutter
      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.9'
          channel: 'stable'
      
      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Run analysis
      #- name: Analyze project source
      #  run: flutter analyze

      # Run test
      #- name: Run tests
      #  run: flutter test

      # Build apk
      - name: Build APK
        run: flutter build apk --release

      # build aab
      - name: Build appBundle
        run: flutter build appbundle

      # Upload Artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Releases
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/bundle/release/app-release.aab

      # Create Release
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/app-release.apk,build/app/outputs/bundle/release/app-release.aab"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
